export { default as chat_logo } from "@/public/imgs/chat/logo.svg"
export { default as phone } from "@/public/imgs/landing/Phone.svg";
export { default as doctor } from "@/public/imgs/landing/doctor.svg";
export { default as medicalTeam } from "@/public/imgs/landing/medical-team.svg";
export { default as hospital } from "@/public/imgs/landing/hospital.svg";
export { default as chat } from "@/public/imgs/landing/chat.svg";
export { default as cross } from "@/public/imgs/landing/cross.svg";
export { default as doctorImg } from "@/public/imgs/doctor/doctor.jpg";
export { default as plus } from "@/public/imgs/services_logo/plus.png";
export { default as check } from "@/public/imgs/services_logo/check.png";
export { default as docService } from "@/public/imgs/services_logo/doctor.png";
export { default as appstore } from "@/public/imgs/landing/appstore.svg";
export { default as googleplay } from "@/public/imgs/landing/googleplay.svg";
export { default as header } from "@/public/imgs/landing/Header.svg";
